// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Scanner.flex

/* ============================================================
 * Scanner.flex
 * JFlex Lexical Specification for RFLang (.rflang)
 *
 * JFlex file has 3 sections separated by %%:
 *   Section 1: User code (imports) — goes ABOVE class in Yylex.java
 *   Section 2: Options, directives, %{code%}, macros
 *   Section 3: Lexical rules
 *
 * Compile: java -jar C:\jflex-1.9.1\lib\jflex-full-1.9.1.jar Scanner.flex
 * Then:    javac Token.java TokenType.java SymbolTable.java ErrorHandler.java Yylex.java
 * Run:     java Yylex ../tests/test1.rflang
 *
 * CS4031 - Compiler Construction - Assignment 01
 * Abdul Raffay (23i-0587) & Ibrahim Azad (23i-3049)
 * ============================================================ */

/* ============================================================
 * SECTION 1: USER CODE  (imports — placed BEFORE first %%)
 * ============================================================ */
import java.io.IOException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;


@SuppressWarnings("fallthrough")
class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\12\23\1\24"+
    "\1\25\1\26\1\27\1\30\2\0\4\31\1\32\25\31"+
    "\1\33\1\34\1\35\1\0\1\36\1\0\4\37\1\40"+
    "\10\37\1\41\3\37\1\41\1\37\1\41\6\37\1\42"+
    "\1\43\1\44\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\6\1\41\1\42\1\43\1\12\1\44\1\12"+
    "\1\45\1\46\1\47\1\0\1\6\1\0\1\42\1\12"+
    "\1\50\1\0\1\51\1\0\1\52\1\53\1\51\1\0"+
    "\1\42\1\51\1\0\4\51\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\45\0\45\0\45\0\112\0\157\0\224"+
    "\0\45\0\271\0\336\0\45\0\45\0\u0103\0\u0128\0\45"+
    "\0\u014d\0\u0172\0\u0197\0\45\0\45\0\112\0\112\0\112"+
    "\0\u01bc\0\45\0\45\0\u01e1\0\45\0\u0206\0\45\0\45"+
    "\0\45\0\u022b\0\u0250\0\u0275\0\45\0\u029a\0\45\0\u02bf"+
    "\0\45\0\45\0\45\0\u02e4\0\u0309\0\u032e\0\u0353\0\u0378"+
    "\0\45\0\u039d\0\u03c2\0\u03e7\0\u040c\0\45\0\u0431\0\u0456"+
    "\0\u040c\0\u047b\0\u04a0\0\u04a0\0\u04c5\0\u04ea\0\u050f\0\u0534";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\2\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\31\1\32\1\2\1\33\1\2\3\34\1\35"+
    "\1\36\1\37\74\0\1\40\15\0\2\7\1\0\3\7"+
    "\1\41\25\7\1\42\10\7\7\0\1\43\5\0\1\44"+
    "\40\0\1\45\33\0\2\46\1\0\7\46\1\47\21\46"+
    "\1\50\10\46\15\0\1\51\11\0\1\52\33\0\1\53"+
    "\10\0\1\52\35\0\1\53\6\0\1\52\44\0\1\52"+
    "\36\0\1\54\1\0\1\23\44\0\1\31\12\0\4\31"+
    "\42\0\3\34\46\0\1\45\1\0\2\55\1\0\3\55"+
    "\1\56\25\55\1\7\4\55\1\7\3\55\2\43\1\0"+
    "\42\43\15\44\1\57\27\44\2\60\1\0\7\60\1\61"+
    "\34\60\1\0\7\60\1\62\21\60\1\46\4\60\1\46"+
    "\3\60\23\0\1\63\21\0\2\55\1\0\3\55\1\0"+
    "\36\55\2\56\1\0\3\56\1\41\25\56\1\64\10\56"+
    "\7\44\1\65\5\44\1\57\27\44\2\60\1\0\7\60"+
    "\1\66\32\60\12\0\1\61\55\0\1\67\6\0\1\70"+
    "\5\0\1\70\12\0\1\56\25\0\1\56\4\0\1\56"+
    "\3\0\45\71\23\0\1\72\6\0\1\70\5\0\1\70"+
    "\22\0\1\73\1\0\1\73\2\0\1\74\44\0\1\75"+
    "\6\0\1\70\5\0\1\70\27\0\1\74\44\0\1\76"+
    "\6\0\1\70\5\0\1\70\27\0\1\77\6\0\1\70"+
    "\5\0\1\70\27\0\1\100\6\0\1\70\5\0\1\70"+
    "\27\0\1\100\21\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1369];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\11\3\1\1\11\2\1\2\11\2\1\1\11"+
    "\3\1\2\11\4\1\2\11\1\1\1\11\1\1\3\11"+
    "\3\1\1\11\1\1\1\11\1\1\3\11\1\0\1\1"+
    "\1\0\2\1\1\11\1\0\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\2\1\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

/* Column tracking (1-based, matches ManualScanner output) */
private int col = 1;
private void resetCol()        { col = 1; }
private void advanceCol(int n) { col += n; }

/* Keyword set */
private static final Set<String> KEYWORDS = new LinkedHashSet<>(Arrays.asList(
    "start", "finish", "loop", "condition", "declare",
    "output", "input", "function", "return", "break",
    "continue", "else"
));

/* Output structures */
private List<Token>             tokens       = new ArrayList<>();
private SymbolTable             symbolTable  = new SymbolTable();
private ErrorHandler            errorHandler = new ErrorHandler();
private Map<TokenType, Integer> tokenCounts  = new LinkedHashMap<>();
private int                     commentsRemoved = 0;

{
    for (TokenType tt : TokenType.values()) {
        if (tt != TokenType.EOF) tokenCounts.put(tt, 0);
    }
}

private void addToken(TokenType type, String lexeme, int line, int startCol) {
    tokens.add(new Token(type, lexeme, line, startCol));
    tokenCounts.put(type, tokenCounts.getOrDefault(type, 0) + 1);
    if (type == TokenType.IDENTIFIER) symbolTable.addIdentifier(lexeme, line, startCol);
}

public List<Token>   getTokens()       { return tokens; }
public SymbolTable   getSymbolTable()  { return symbolTable; }
public ErrorHandler  getErrorHandler() { return errorHandler; }

public void displayTokens() {
    System.out.println("\n========================================");
    System.out.println("         TOKEN OUTPUT");
    System.out.println("========================================");
    for (Token t : tokens) System.out.println("  " + t);
    System.out.println("========================================\n");
}

public void displayStatistics() {
    int total = 0;
    for (int v : tokenCounts.values()) total += v;
    System.out.println("\n========================================");
    System.out.println("         SCANNER STATISTICS");
    System.out.println("========================================");
    System.out.printf("  Total tokens:       %d%n", total);
    System.out.printf("  Lines processed:    %d%n", yyline + 1);
    System.out.printf("  Comments removed:   %d%n", commentsRemoved);
    System.out.println("  ----------------------------------------");
    System.out.println("  Token Count by Type:");
    for (Map.Entry<TokenType, Integer> e : tokenCounts.entrySet()) {
        if (e.getValue() > 0)
            System.out.printf("    %-25s %d%n", e.getKey(), e.getValue());
    }
    System.out.println("========================================\n");
}

public static void main(String[] args) throws IOException {
    if (args.length < 1) {
        System.out.println("Usage: java Yylex <source-file>");
        System.exit(1);
    }
    String filename = args[0];
    System.out.println("=== JFlex Scanner - CS4031 Compiler Construction ===");
    System.out.println("Scanning file: " + filename);
    Yylex scanner;
    try {
        scanner = new Yylex(new FileReader(filename));
    } catch (IOException e) {
        System.err.println("Error: Could not open file '" + filename + "'");
        System.exit(1); return;
    }
    try { scanner.yylex(); } catch (IOException e) { System.err.println("I/O error: " + e.getMessage()); }
    scanner.displayTokens();
    scanner.displayStatistics();
    scanner.getSymbolTable().display();
    scanner.getErrorHandler().displayErrors();
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public void yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   return;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { int startCol = col; advanceCol(1);
    errorHandler.reportInvalidCharacter(yyline+1, startCol, yytext().charAt(0));
    addToken(TokenType.ERROR, yytext(), yyline+1, startCol);
            }
          // fall through
          case 45: break;
          case 2:
            { advanceCol(1);
            }
          // fall through
          case 46: break;
          case 3:
            { resetCol();
            }
          // fall through
          case 47: break;
          case 4:
            { /* skip */
            }
          // fall through
          case 48: break;
          case 5:
            { int c = col; advanceCol(1); addToken(TokenType.LOGICAL_OPERATOR,     "!", yyline+1, c);
            }
          // fall through
          case 49: break;
          case 6:
            { int startCol = col; advanceCol(yytext().length());
    errorHandler.reportError("UNTERMINATED_STRING", yyline+1, startCol, yytext(),
        "String literal not closed before end of line");
    addToken(TokenType.ERROR, yytext(), yyline+1, startCol);
            }
          // fall through
          case 50: break;
          case 7:
            { int startCol = col; advanceCol(1);
    errorHandler.reportError("INVALID_CHARACTER", yyline+1, startCol, "#",
        "Lone '#' is not valid; use ## for single-line or #* *# for multi-line comments");
    addToken(TokenType.ERROR, "#", yyline+1, startCol);
            }
          // fall through
          case 51: break;
          case 8:
            { int c = col; advanceCol(1); addToken(TokenType.ARITHMETIC_OPERATOR, "%", yyline+1, c);
            }
          // fall through
          case 52: break;
          case 9:
            { int startCol = col; advanceCol(1);
    errorHandler.reportError("INVALID_CHARACTER", yyline+1, startCol, "&",
        "Single '&' is not valid; use '&&' for logical AND");
    addToken(TokenType.ERROR, "&", yyline+1, startCol);
            }
          // fall through
          case 53: break;
          case 10:
            { int startCol = col; advanceCol(yytext().length());
    errorHandler.reportError("UNTERMINATED_CHAR", yyline+1, startCol, yytext(),
        "Character literal was not closed");
    addToken(TokenType.ERROR, yytext(), yyline+1, startCol);
            }
          // fall through
          case 54: break;
          case 11:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, "(", yyline+1, c);
            }
          // fall through
          case 55: break;
          case 12:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, ")", yyline+1, c);
            }
          // fall through
          case 56: break;
          case 13:
            { int c = col; advanceCol(1); addToken(TokenType.ARITHMETIC_OPERATOR, "*", yyline+1, c);
            }
          // fall through
          case 57: break;
          case 14:
            { int c = col; advanceCol(1); addToken(TokenType.ARITHMETIC_OPERATOR, "+", yyline+1, c);
            }
          // fall through
          case 58: break;
          case 15:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, ",", yyline+1, c);
            }
          // fall through
          case 59: break;
          case 16:
            { int c = col; advanceCol(1); addToken(TokenType.ARITHMETIC_OPERATOR, "-", yyline+1, c);
            }
          // fall through
          case 60: break;
          case 17:
            { int c = col; advanceCol(1); addToken(TokenType.ARITHMETIC_OPERATOR, "/", yyline+1, c);
            }
          // fall through
          case 61: break;
          case 18:
            { int startCol = col; advanceCol(yytext().length());
    addToken(TokenType.INTEGER_LITERAL, yytext(), yyline+1, startCol);
            }
          // fall through
          case 62: break;
          case 19:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, ":", yyline+1, c);
            }
          // fall through
          case 63: break;
          case 20:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, ";", yyline+1, c);
            }
          // fall through
          case 64: break;
          case 21:
            { int c = col; advanceCol(1); addToken(TokenType.RELATIONAL_OPERATOR,  "<", yyline+1, c);
            }
          // fall through
          case 65: break;
          case 22:
            { int c = col; advanceCol(1); addToken(TokenType.ASSIGNMENT_OPERATOR,  "=", yyline+1, c);
            }
          // fall through
          case 66: break;
          case 23:
            { int c = col; advanceCol(1); addToken(TokenType.RELATIONAL_OPERATOR,  ">", yyline+1, c);
            }
          // fall through
          case 67: break;
          case 24:
            { String lex = yytext();
    int startLine = yyline + 1;
    int startCol  = col;
    advanceCol(lex.length());
    if (lex.length() > 31) {
        errorHandler.reportInvalidIdentifier(startLine, startCol, lex,
            "Identifier exceeds maximum length of 31 characters (length=" + lex.length() + ")");
        addToken(TokenType.ERROR, lex, startLine, startCol);
    } else {
        addToken(TokenType.IDENTIFIER, lex, startLine, startCol);
    }
            }
          // fall through
          case 68: break;
          case 25:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, "[", yyline+1, c);
            }
          // fall through
          case 69: break;
          case 26:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, "]", yyline+1, c);
            }
          // fall through
          case 70: break;
          case 27:
            { String word = yytext();
    int startLine = yyline + 1;
    int startCol  = col;
    advanceCol(word.length());
    if (KEYWORDS.contains(word)) {
        addToken(TokenType.KEYWORD, word, startLine, startCol);
    } else if (word.equals("true") || word.equals("false")) {
        addToken(TokenType.BOOLEAN_LITERAL, word, startLine, startCol);
    } else {
        errorHandler.reportInvalidIdentifier(startLine, startCol, word,
            "'" + word + "' is not a keyword or boolean; identifiers must start with uppercase");
        addToken(TokenType.ERROR, word, startLine, startCol);
    }
            }
          // fall through
          case 71: break;
          case 28:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, "{", yyline+1, c);
            }
          // fall through
          case 72: break;
          case 29:
            { int startCol = col; advanceCol(1);
    errorHandler.reportError("INVALID_CHARACTER", yyline+1, startCol, "|",
        "Single '|' is not valid; use '||' for logical OR");
    addToken(TokenType.ERROR, "|", yyline+1, startCol);
            }
          // fall through
          case 73: break;
          case 30:
            { int c = col; advanceCol(1); addToken(TokenType.PUNCTUATOR, "}", yyline+1, c);
            }
          // fall through
          case 74: break;
          case 31:
            { int c = col; advanceCol(2); addToken(TokenType.RELATIONAL_OPERATOR, yytext(), yyline+1, c);
            }
          // fall through
          case 75: break;
          case 32:
            { int startCol = col; advanceCol(yytext().length());
    addToken(TokenType.STRING_LITERAL, yytext(), yyline+1, startCol);
            }
          // fall through
          case 76: break;
          case 33:
            { int startCol = col;
    advanceCol(yytext().length());
    addToken(TokenType.SINGLE_LINE_COMMENT, yytext(), yyline + 1, startCol);
    commentsRemoved++;
            }
          // fall through
          case 77: break;
          case 34:
            { int startLine = yyline + 1;
    int startCol  = col;
    String txt = yytext();
    for (int i = 0; i < txt.length(); i++) {
        if (txt.charAt(i) == '\n') resetCol(); else advanceCol(1);
    }
    errorHandler.reportError("UNCLOSED_COMMENT", startLine, startCol, txt,
        "Multi-line comment opened with #* but never closed with *#");
    addToken(TokenType.ERROR, txt, startLine, startCol);
            }
          // fall through
          case 78: break;
          case 35:
            { int c = col; advanceCol(2); addToken(TokenType.LOGICAL_OPERATOR,    yytext(), yyline+1, c);
            }
          // fall through
          case 79: break;
          case 36:
            { int startCol = col; advanceCol(2);
    errorHandler.reportError("EMPTY_CHAR", yyline+1, startCol, "''", "Empty character literal");
    addToken(TokenType.ERROR, "''", yyline+1, startCol);
            }
          // fall through
          case 80: break;
          case 37:
            { int c = col; advanceCol(2); addToken(TokenType.ARITHMETIC_OPERATOR, yytext(), yyline+1, c);
            }
          // fall through
          case 81: break;
          case 38:
            { int c = col; advanceCol(2); addToken(TokenType.ASSIGNMENT_OPERATOR, yytext(), yyline+1, c);
            }
          // fall through
          case 82: break;
          case 39:
            { int c = col; advanceCol(2); addToken(TokenType.INC_DEC_OPERATOR,    yytext(), yyline+1, c);
            }
          // fall through
          case 83: break;
          case 40:
            { int startCol = col; advanceCol(yytext().length());
    addToken(TokenType.CHAR_LITERAL, yytext(), yyline+1, startCol);
            }
          // fall through
          case 84: break;
          case 41:
            { int startCol = col; advanceCol(yytext().length());
    addToken(TokenType.FLOAT_LITERAL, yytext(), yyline+1, startCol);
            }
          // fall through
          case 85: break;
          case 42:
            { int startLine = yyline + 1;
    int startCol  = col;
    String txt = yytext();
    for (int i = 0; i < txt.length(); i++) {
        if (txt.charAt(i) == '\n') resetCol(); else advanceCol(1);
    }
    addToken(TokenType.MULTI_LINE_COMMENT, txt, startLine, startCol);
    commentsRemoved++;
            }
          // fall through
          case 86: break;
          case 43:
            { String lex = yytext();
    int startCol = col; advanceCol(lex.length());
    errorHandler.reportError("MULTI_CHAR_LITERAL", yyline+1, startCol, lex,
        "Character literal contains more than one character");
    addToken(TokenType.ERROR, lex, yyline+1, startCol);
            }
          // fall through
          case 87: break;
          case 44:
            { String lex = yytext();
    int startCol = col; advanceCol(lex.length());
    String dec = lex.substring(lex.indexOf('.') + 1);
    errorHandler.reportMalformedFloat(yyline+1, startCol, lex,
        "Float has " + dec.length() + " decimal digits; maximum allowed is 6");
    addToken(TokenType.ERROR, lex, yyline+1, startCol);
            }
          // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
